#Ya, this should all be in a nicer format
#When I started, I thought "Oh, I only have 10 or so entries, I can just make a dictionary

st_buffers = ["Sunday", "Sparkle", "Bronya", "RMC", "Tingyun"]

buffs = {
  "Phainon": {
    "base_atk": 562.72,
    "atk_p": 195,
    "atk": 450,
    "p": 38.8,
    "cr": 90,
    "cd": 145,
    "res": 0,
  },
  "relics": {
    "atk_p": 48,
    "cd": 16,
    "p": 36
  },
  "lc": {
    "base_atk": 529,
    "atk_p": 64,
    "p":24
  },
  "generic_st": {
    "cd": 36,
    "p": 32
  },
  "Sunday": {
    "p": 80,
    "cr": 20,
    "cd": 97
  },
  "Sparkle": {
    "atk_p": 15,
    "p": 48,
    "cd": 115,
  },
  "Bronya": {
    "atk_p": 55,
    "p": 76,
    "cd": 70
  },
  "RMC": {
    "p": 16,
    "cr": 10,
    "cd": 70,
    "true_dmg": 30
  },
  "Tingyun": {
    "atk": 810,
    "p": 56,
    "cd": 10
  },
  "Robin": {
    "atk_p": 12, #lushaka
    "atk": 1200,
    "p": 50,
    "cd": 20
  },
  "Cipher": {
    "vuln": 40,
    "true_dmg": 24,
    # "def_shred": 12
  },
  "Tribbie": {
    "vuln": 30,
    "res_pen": 24
  },
  "RuanMei": {
    "p": 68,
    "res_pen": 25
  },
  "Yukong": {
    "atk_p": 80,
    "cr": 29.4,
    "cd": 80.2
  },
  "Aventurine": {
    "p": 40,
    "cd": 10
  },
  "FuXuan": {
    "p": 40,
    "cd": 10,
    "cr": 12
  },
  "Huohuo": {
    "p": 40,
    "atk_p": 40,
    "cd": 25
  }, 
  "Gallagher": {
    "p": 40,
    "cd": 25
  }, 
  "Jiaoqiu": {
    "vuln": 38 #assumes 20% is ult damage and it's evenly distributed
  }
}

image_urls = {
  "Tribbie-Tingyun-Huohuo": "https://drive.google.com/uc?export=view&id=1-2wggafGpkohWBCKzgbp-4yOaglu_XX-",
  "Robin-Yukong-Tingyun": "https://drive.google.com/uc?export=view&id=1-B2ZmLV-8XmrTYqGz5mXxvNlV7nZWXng",
  "Yukong-RMC-Huohuo": "https://drive.google.com/uc?export=view&id=1-CRM7AqSHNWnxHYqjKCmCnHpHT0vmZWj",
  "Tribbie-Sunday-Tingyun": "https://drive.google.com/uc?export=view&id=1-DpCWaMaZBgh7Td9jzVbqnut2ThSB1Oe",
  "Robin-Bronya-Huohuo": "https://drive.google.com/uc?export=view&id=1-xaCAcMysO9tZ1PnKSmpouwMpOypY-Ug",
  "Robin-Sparkle-FuXuan": "https://drive.google.com/uc?export=view&id=117YwcOs1iCwxm92kEdTtCtYz8Ptu_h7S",
  "Robin-Yukong-RMC": "https://drive.google.com/uc?export=view&id=128-0-sMA6EAq6uvwg_uV_M6-4ICHIrwT",
  "Robin-Cipher-Tingyun": "https://drive.google.com/uc?export=view&id=12JMIYSNUQDI3PFzcRc5I_cJedDG1Hs4O",
  "Robin-Sparkle-RMC": "https://drive.google.com/uc?export=view&id=12Z1vYgkGL_yJXuJt_ElpHpUgZ39Ra2_8",
  "Tribbie-Sunday-Huohuo": "https://drive.google.com/uc?export=view&id=13gfJAJZ5nsk7Uk5aNFc5ZXazNLaenapi",
  "RuanMei-Tingyun-FuXuan": "https://drive.google.com/uc?export=view&id=13oF_Mfxyvdc8O_hyOm3ur1Z02vnh0HuX",
  "Robin-Tribbie-Bronya": "https://drive.google.com/uc?export=view&id=14617NgLsAaiumDG3DI1CnJ5zpsAB8paB",
  "Tribbie-RMC-Aventurine": "https://drive.google.com/uc?export=view&id=14N2pMqfRGsxQ053pQML3vnvUqq5W2WTE",
  "Tribbie-Sparkle-Aventurine": "https://drive.google.com/uc?export=view&id=158lhXt4SWmwsEiWgacVuzEIwybo2PXOp",
  "RuanMei-Sparkle-RMC": "https://drive.google.com/uc?export=view&id=15jRNGSl7HFwPQprctlj1PAW22cVVPo1Q",
  "Tribbie-RMC-FuXuan": "https://drive.google.com/uc?export=view&id=16IKIZIWOhzAPIaHnaIlrzetM0xdvMV4J",
  "Yukong-Sparkle-Tingyun": "https://drive.google.com/uc?export=view&id=179BzgRgNm7Cv78izbmiRbsakvyX1_X1i",
  "Tribbie-Sunday-Gallagher": "https://drive.google.com/uc?export=view&id=17cqqPI1uccAleXxkWaViFULpSk6hwR6e",
  "Robin-Bronya-RMC": "https://drive.google.com/uc?export=view&id=17i6JMfZ4ERneunR3ZdkOM7ucfyttn9qV",
  "Cipher-Sparkle-RMC": "https://drive.google.com/uc?export=view&id=17phUuWQmaTYjrg6m_EyQrgjvdVjwLJP-",
  "Robin-Yukong-Sunday": "https://drive.google.com/uc?export=view&id=17xpmBaoZx8M0FQlVlYFa87xpzspysj6V",
  "Cipher-RMC-Aventurine": "https://drive.google.com/uc?export=view&id=185KN85AIRo4Z3TyYmd4cFe3ZVI6yBKF6",
  "RuanMei-Sunday-Gallagher": "https://drive.google.com/uc?export=view&id=18GhpztTm0YsoUy2cgRV-CchBtzsIdhw3",
  "Cipher-Tingyun-Gallagher": "https://drive.google.com/uc?export=view&id=18VmgdFPZDALUqon6Jy12IZ41DrPAYao1",
  "Tribbie-Sparkle-Bronya": "https://drive.google.com/uc?export=view&id=18WDqiLEQJkkVTgdHiogP6RH7HgE4lLcr",
  "Tribbie-Bronya-Aventurine": "https://drive.google.com/uc?export=view&id=18YHfDiW5Csv_ZcwuB5V3CTWICoY0rieD",
  "Yukong-Bronya-Tingyun": "https://drive.google.com/uc?export=view&id=18jr_ZXwI9OscMU97mwoyXDxdOuX_8wEZ",
  "RuanMei-RMC-Gallagher": "https://drive.google.com/uc?export=view&id=18ySZIyZJn634KRuXEjMreAqW41JCAJIz",
  "Robin-RuanMei-Sunday": "https://drive.google.com/uc?export=view&id=19HXItIygI7kMkni24oIOTJf1TyugD6di",
  "Cipher-Sparkle-Bronya": "https://drive.google.com/uc?export=view&id=19R9tKCaRnXR4rla3ZYAfn-1KntgWxQJv",
  "Robin-Tribbie-Sunday": "https://drive.google.com/uc?export=view&id=19Z4l6bM2hdiVGf5ai3c8_Y9fvPPKvEA7",
  "Robin-Cipher-Bronya": "https://drive.google.com/uc?export=view&id=19Z7x3JsB_IUUtkNwGlt6DedBKqpurqJK",
  "Tribbie-Sunday-Bronya": "https://drive.google.com/uc?export=view&id=19hyxo4uNni0eETz3HQedqh2FmFJ9g5NU",
  "Cipher-Sunday-Gallagher": "https://drive.google.com/uc?export=view&id=19qmIBvvi9tnpNfT_j73PpGueDAvtgBaQ",
  "RuanMei-RMC-FuXuan": "https://drive.google.com/uc?export=view&id=19vyRWGRczRbNxbYs3zZScNecdb1Qi__W",
  "Yukong-RMC-Aventurine": "https://drive.google.com/uc?export=view&id=1A1qnVZblVzdPKr1qqOms9pcqtly4W62x",
  "RuanMei-Bronya-RMC": "https://drive.google.com/uc?export=view&id=1ABKvbgY_EzOnJ8H69aN7dHfWT5a8fLaJ",
  "RuanMei-Sunday-Bronya": "https://drive.google.com/uc?export=view&id=1ALuD_9-hiXwpMuHPonX7Kz_xn798oT19",
  "Robin-Bronya-Gallagher": "https://drive.google.com/uc?export=view&id=1AZGM7Zs5vrHCdqe7mEFUVQC6c4hFfR-L",
  "Robin-Bronya-FuXuan": "https://drive.google.com/uc?export=view&id=1AoKvqz8uybHhIJzLXazfhZBN7Cyt1mjS",
  "Robin-Sparkle-Tingyun": "https://drive.google.com/uc?export=view&id=1B1n5LX6D1MqRcms586vGg7If8gfd4IG7",
  "Robin-Bronya-Aventurine": "https://drive.google.com/uc?export=view&id=1BYdS67Uxvx0yyeVmMbud0uNHjz8_fnSh",
  "Cipher-Sunday-Bronya": "https://drive.google.com/uc?export=view&id=1CEjVngWCa790TaOEEuUU0n6ZJMvqccWb",
  "Robin-Sunday-Gallagher": "https://drive.google.com/uc?export=view&id=1DQGwpSLk6KuUec1cBKfKSXGrmXZBDZX1",
  "Yukong-Sunday-FuXuan": "https://drive.google.com/uc?export=view&id=1Dsq0ygunYA2MgPeFirgsbBA2ck0hHmeR",
  "RuanMei-RMC-Huohuo": "https://drive.google.com/uc?export=view&id=1F-x5AfbNkFdjfoIe7-daP2JSG4v46VnO",
  "RuanMei-Sparkle-Gallagher": "https://drive.google.com/uc?export=view&id=1FDJkrMRm1-jizZeXuVf8ji_zLbS63H0u",
  "Yukong-Bronya-Gallagher": "https://drive.google.com/uc?export=view&id=1FSyWE0nIIGWEYGELoyfWGIbUfZdccPBX",
  "Robin-RMC-Gallagher": "https://drive.google.com/uc?export=view&id=1FzFjAx8ulLUXOzCdkHhDEUBJHR3VXih-",
  "Yukong-Bronya-FuXuan": "https://drive.google.com/uc?export=view&id=1G-TJdnQ2w-c1wzYfunCnJuYkHR73YhWl",
  "Cipher-Bronya-Tingyun": "https://drive.google.com/uc?export=view&id=1G3x_JJbYIlDBFDkGhV0RNz2VBbc3QE_Y",
  "Sparkle-Bronya-RMC": "https://drive.google.com/uc?export=view&id=1G7KEur-HaWxovYAhLH0WCYgp4efFGCUK",
  "Robin-Sunday-Aventurine": "https://drive.google.com/uc?export=view&id=1GK6JRMwg6RD0nAIQEp33SfG0LgZQA6J1",
  "Tribbie-Sparkle-Huohuo": "https://drive.google.com/uc?export=view&id=1GYv0gr_Obtjyf0KUohisz-4uAobQ8Yr8",
  "Cipher-Bronya-RMC": "https://drive.google.com/uc?export=view&id=1GlGbJcxgnq64qzH_nKniM1DDPA0-QbDP",
  "RuanMei-Tingyun-Gallagher": "https://drive.google.com/uc?export=view&id=1GvaTH6RVcudtItrjyJ5uxXFBaPjWdAn9",
  "Sunday-Sparkle-Bronya": "https://drive.google.com/uc?export=view&id=1HDX1hHKRA4miAPT10TJiPCge_dGSfLc3",
  "Robin-RMC-Huohuo": "https://drive.google.com/uc?export=view&id=1HS53rv-Gv2xO6nZkxOX90AsB_eaUoG1U",
  "Robin-RuanMei-Tingyun": "https://drive.google.com/uc?export=view&id=1HXQMXhOQtdfqC6ascq4vDQdW1StaGY9R",
  "Cipher-RMC-Tingyun": "https://drive.google.com/uc?export=view&id=1Hg0RqJpzgGR-nIckM71DHb47Pv8cxYVX",
  "Tribbie-RMC-Tingyun": "https://drive.google.com/uc?export=view&id=1HuygYfmEcI5OmwuGzuGIheYkMN89RtPc",
  "Robin-Cipher-Sparkle": "https://drive.google.com/uc?export=view&id=1INNOGkygeqno7MSal1hhCtc-7RrOQkIi",
  "Robin-Sparkle-Huohuo": "https://drive.google.com/uc?export=view&id=1IbUfeFcAOT9AVfgKqXatRAjVtLwOyxBT",
  "Bronya-RMC-Tingyun": "https://drive.google.com/uc?export=view&id=1Iccap2mg8wtgck-34y2lVMVgMhyHhnnc",
  "Yukong-RMC-Gallagher": "https://drive.google.com/uc?export=view&id=1Id-tJk5BrsRPM8Z15ctsNnrZJZnM1r75",
  "RuanMei-Sunday-Tingyun": "https://drive.google.com/uc?export=view&id=1JAqNqng5Le-TFVPGYOpilvQ__O0Bg4q3",
  "Cipher-Tingyun-Aventurine": "https://drive.google.com/uc?export=view&id=1JnuE4XlDDnPAQEJ1ZX7V_1SANqRqMwCC",
  "RuanMei-Bronya-Gallagher": "https://drive.google.com/uc?export=view&id=1K6Lzzukvv8APH8m0QU3i-FhAbvH9Ypbj",
  "Tribbie-Bronya-RMC": "https://drive.google.com/uc?export=view&id=1KCQxMuS2QvRYaP7NG2SlxqanYZyM_bT7",
  "Yukong-Sunday-Huohuo": "https://drive.google.com/uc?export=view&id=1KlKilOBaa0NikHzAZiEOsMV76aI67dJo",
  "Tribbie-Bronya-Gallagher": "https://drive.google.com/uc?export=view&id=1L3VyXHPCIS4-BcYUx1amc_H11sZ1Xd5W",
  "RuanMei-RMC-Aventurine": "https://drive.google.com/uc?export=view&id=1LR6do4YIe-729uxIBJUcTAzk-KIRmpJo",
  "Robin-Sunday-Tingyun": "https://drive.google.com/uc?export=view&id=1LZuttvyxMtZvxpc0PzMWjqy_tSmlwwIZ",
  "RuanMei-Bronya-FuXuan": "https://drive.google.com/uc?export=view&id=1LfiQh1ptMQLtjanJY-DmF79AxT96RBAw",
  "Robin-Sunday-FuXuan": "https://drive.google.com/uc?export=view&id=1Lz-Kg90PLkWvqw2bvK5ds2JaEi6ttWO1",
  "Sparkle-RMC-Tingyun": "https://drive.google.com/uc?export=view&id=1M3MA_0UQx4w_5VfJ_irBBsNogryhg_Oy",
  "Yukong-RMC-Tingyun": "https://drive.google.com/uc?export=view&id=1MX7ADWGXOL0_z6QqLnSjAIhRJSyKMdB_",
  "Cipher-Sunday-FuXuan": "https://drive.google.com/uc?export=view&id=1MdWt3LIQE9fFSB7ascuaHjB7Oz02LcTc",
  "Robin-Yukong-Sparkle": "https://drive.google.com/uc?export=view&id=1NBGwQTlGLYWOgnZFtGFWYMZbJbMWDI-4",
  "RuanMei-Sparkle-Tingyun": "https://drive.google.com/uc?export=view&id=1NlOtStLCzximF6GJ-VHjcRG60Lf-y-Zc",
  "Cipher-Sunday-Huohuo": "https://drive.google.com/uc?export=view&id=1NsGDgx0LvK2Oj6ykEDQUuqQgRQwpUZ3W",
  "Robin-Tribbie-Sparkle": "https://drive.google.com/uc?export=view&id=1OnBFUesVCMAVnisIK8SxWTBJR0LtIJMl",
  "Tribbie-Sunday-FuXuan": "https://drive.google.com/uc?export=view&id=1OnuL_cOhGDeu4YdAcDeZMZ-ZDLfHzqhd",
  "Robin-Cipher-Sunday": "https://drive.google.com/uc?export=view&id=1PJmEp3_lUyOqNMGi6Tv5fko3tMIuYwHe",
  "Cipher-Sunday-Aventurine": "https://drive.google.com/uc?export=view&id=1PUvtFzEKIW0WTZozxKi--O9-2G0yJ5LT",
  "Robin-RuanMei-Sparkle": "https://drive.google.com/uc?export=view&id=1PwuKejKf2fbkz_Y7RF9R_-SlNGSu1T-l",
  "Tribbie-RMC-Huohuo": "https://drive.google.com/uc?export=view&id=1QHCQlmejpO7eYK4ugNllh07kfi0s88Qi",
  "Yukong-Bronya-RMC": "https://drive.google.com/uc?export=view&id=1RQk3JR4BCVjIfNZ6L5CmLwKFDT2o5-R9",
  "RuanMei-Bronya-Huohuo": "https://drive.google.com/uc?export=view&id=1R_HcxJcIXuAIDo4CCKyuokroNLoh0ATZ",
  "Robin-Tingyun-Gallagher": "https://drive.google.com/uc?export=view&id=1RjiQBkQVVzTuwC78vHM1bsPFRjafGfrh",
  "Tribbie-Tingyun-Gallagher": "https://drive.google.com/uc?export=view&id=1SOGNe_5fmZAWnShiUpS4wHrgoNcNUclQ",
  "RuanMei-Tingyun-Aventurine": "https://drive.google.com/uc?export=view&id=1SOwOrK4AI8nxopBu_w5lQPg3UlYfhS9w",
  "Yukong-Sparkle-Huohuo": "https://drive.google.com/uc?export=view&id=1SptGrCZdYRzMSoQ1OdtcsPBQJWVdNMxC",
  "Cipher-Sunday-Tingyun": "https://drive.google.com/uc?export=view&id=1TGVIO8JNlsLhZ2jk1DZh4RTGpsFwOKpk",
  "Sunday-Bronya-RMC": "https://drive.google.com/uc?export=view&id=1TOn1UYGEFP6NoXXHxbd8izYL7pwjFk6V",
  "Yukong-Bronya-Huohuo": "https://drive.google.com/uc?export=view&id=1Tkyg_vALf3rm5n8ZOk5BAo1cIRfx4Icb",
  "RuanMei-Sparkle-Aventurine": "https://drive.google.com/uc?export=view&id=1U_ejfBHqdKLG_wAsSIXl-WcH5PVjTn8l",
  "Robin-RuanMei-RMC": "https://drive.google.com/uc?export=view&id=1UaIvJgNpUXkVjpSMAsUlKEPDZi1mo7PN",
  "Robin-RMC-Tingyun": "https://drive.google.com/uc?export=view&id=1VUQbQnte0Lh4lgLXWboos7wdLCYtcuv5",
  "Robin-RMC-Aventurine": "https://drive.google.com/uc?export=view&id=1Vd_Ye_0UElwEEvDoE4t91d0GDlsSftav",
  "Yukong-Sparkle-FuXuan": "https://drive.google.com/uc?export=view&id=1WmZWgQgTt5IWdEgFaEmWmSyggFQTo13X",
  "Cipher-Tingyun-FuXuan": "https://drive.google.com/uc?export=view&id=1Wr3KJAX5WH-Saa8jGjju2-riaICFveWw",
  "Sparkle-Bronya-Tingyun": "https://drive.google.com/uc?export=view&id=1XTWrQBUX6FSkR9WAHjJ8b3CJSyMvPr96",
  "Sunday-Sparkle-RMC": "https://drive.google.com/uc?export=view&id=1XXXVy60_DnNdY2GTpI21VBq92-YRoPZy",
  "Tribbie-Sunday-Aventurine": "https://drive.google.com/uc?export=view&id=1XjuJ7mOGO7_aeoPhZAkP7HIARlUkY6YY",
  "Cipher-Bronya-Gallagher": "https://drive.google.com/uc?export=view&id=1Y6N8ajyVF4mRfPQu6PWm_fPFxeHVCNFL",
  "Cipher-RMC-Gallagher": "https://drive.google.com/uc?export=view&id=1YBf6OmBErZ_31twP8U3EZe7Ov-rYJd5K",
  "Cipher-RMC-FuXuan": "https://drive.google.com/uc?export=view&id=1YJT497D9_S4jGMvraS2mkox_mQ5GA8X9",
  "RuanMei-Sunday-Aventurine": "https://drive.google.com/uc?export=view&id=1YZ-R0t4-49k061scBNvZhxaKEeyYzfUE",
  "Tribbie-Bronya-Huohuo": "https://drive.google.com/uc?export=view&id=1YyoQ_oalINxTdibAcox3ybAYl8ykHKbA",
  "Yukong-Sparkle-Gallagher": "https://drive.google.com/uc?export=view&id=1Z31LrKsS0OY0bVtz39-Cw23q0nzZc_DS",
  "Robin-Tingyun-FuXuan": "https://drive.google.com/uc?export=view&id=1ZSGProux3kJlhRqtv6bkCnocI_hwnY92",
  "Cipher-Sparkle-FuXuan": "https://drive.google.com/uc?export=view&id=1Z_mtUjw5zjdDdibbagvZF9LcHdIc1-Nv",
  "Yukong-Sunday-RMC": "https://drive.google.com/uc?export=view&id=1Zuh-kupWAtSRT2MuEwmhMJZ7dw5jMk8M",
  "Sunday-Bronya-Tingyun": "https://drive.google.com/uc?export=view&id=1_QKG_mhkjlPfaqRmInHfGvlWmpqh6fTH",
  "Robin-Sparkle-Aventurine": "https://drive.google.com/uc?export=view&id=1aMRv6wf-ObO8AdrqXen9jC8Fc2mtqy79",
  "Robin-Tingyun-Aventurine": "https://drive.google.com/uc?export=view&id=1c4QNeUyG1WmfHWgRrtk_ksTTwVvG4Qrt",
  "RuanMei-Sparkle-FuXuan": "https://drive.google.com/uc?export=view&id=1d_yd24uoBib0_U2nvKg2agtLkApC6eHe",
  "Robin-Bronya-Tingyun": "https://drive.google.com/uc?export=view&id=1dqQOWIuwk6D1cO_Ooyw1Q8A7PsHZwrfF",
  "Cipher-Sparkle-Huohuo": "https://drive.google.com/uc?export=view&id=1eBq-hEup6h2kalVcyY36AZT0v1Zy8npC",
  "Cipher-Bronya-FuXuan": "https://drive.google.com/uc?export=view&id=1euE31E-HNP5P6eX8UFcLxZ2vt8evpN3Z",
  "Yukong-Tingyun-Aventurine": "https://drive.google.com/uc?export=view&id=1fYu4zGhBnEqRTzuhFzr0BjDEDMS0v_-5",
  "Yukong-Sunday-Sparkle": "https://drive.google.com/uc?export=view&id=1fcSZxizP5prWf0oaaWsdiXxwoiDM11GM",
  "Robin-Sunday-Sparkle": "https://drive.google.com/uc?export=view&id=1fn0-sOsPYs8YMp4JnN4WzHzi1a8C4JoY",
  "Robin-Sparkle-Bronya": "https://drive.google.com/uc?export=view&id=1g1D402xK3OGJojSmoDDdYEA9_xFM1_Ml",
  "Robin-Sunday-Huohuo": "https://drive.google.com/uc?export=view&id=1g7yey6Zdea1KfNxRlSuXchiOl5xa94f1",
  "Tribbie-Sparkle-Tingyun": "https://drive.google.com/uc?export=view&id=1gW-JT4Z2GYXCPeJ5XzdlVr-WgCXD-cdl",
  "RuanMei-Sunday-FuXuan": "https://drive.google.com/uc?export=view&id=1ggLcam2fe5RVk-gb2MdlvRAlTI2TdG2_",
  "Tribbie-Sparkle-Gallagher": "https://drive.google.com/uc?export=view&id=1gqI8Rq_0ZjliJPNEi-OOE_32rQW_gJDK",
  "RuanMei-Sparkle-Huohuo": "https://drive.google.com/uc?export=view&id=1hEeu6xGC06Ljmk8vZ1-Y0n6ChKgEkNwK",
  "Yukong-RMC-FuXuan": "https://drive.google.com/uc?export=view&id=1iZAOYrAu5ZuioovJb7YDAVmC1T1pstsw",
  "Cipher-Tingyun-Huohuo": "https://drive.google.com/uc?export=view&id=1j4t41hz-ItPIRizRFjMdYGQLUWa938bJ",
  "Tribbie-Sparkle-RMC": "https://drive.google.com/uc?export=view&id=1jJh4TZVGHXfIQSWMDeEr0ylDoSUIrQ1n",
  "Cipher-Sparkle-Tingyun": "https://drive.google.com/uc?export=view&id=1jtrvS3B6rA_0DAscLOvIz5rcfPeht9B0",
  "Tribbie-Tingyun-FuXuan": "https://drive.google.com/uc?export=view&id=1jwtXtv9GNbxghrMzqmbeJIWMcOtExYRF",
  "Cipher-Sparkle-Aventurine": "https://drive.google.com/uc?export=view&id=1kNtFaXN7ud3JqJqXkwuxJNA9_Zl5ebyk",
  "Robin-Cipher-RMC": "https://drive.google.com/uc?export=view&id=1kSqXXDDasrzioBIuPzNgCopXof5QjWl9",
  "RuanMei-Bronya-Aventurine": "https://drive.google.com/uc?export=view&id=1kjAp16u7YBgbipxtlBOcNuiB_fBMzjqR",
  "Robin-Tribbie-Tingyun": "https://drive.google.com/uc?export=view&id=1kqtYcHG-_dVESRZP6AOTQEURVzFDHfpO",
  "Robin-Tingyun-Huohuo": "https://drive.google.com/uc?export=view&id=1kxVRWun7IPkEB0clcUjHHdsNGKscOOnZ",
  "RuanMei-Bronya-Tingyun": "https://drive.google.com/uc?export=view&id=1lNtKkxuxqtq93KU2O4nRhEd9WtRCsooE",
  "Tribbie-Sparkle-FuXuan": "https://drive.google.com/uc?export=view&id=1lvmXn2YZCIL9OBQ7LI5TVeuUzwlCQ5q5",
  "Robin-Tribbie-RMC": "https://drive.google.com/uc?export=view&id=1mGD1yxD7fivCLRURNEx6DryXmmYF-d6o",
  "Yukong-Tingyun-Huohuo": "https://drive.google.com/uc?export=view&id=1mr8WJHWObv64C0b8lksaqZcP1jSj_Cwt",
  "Cipher-RMC-Huohuo": "https://drive.google.com/uc?export=view&id=1nByHNGk1du72m3JE9KO4ASpYaN3g0CpR",
  "Yukong-Sparkle-RMC": "https://drive.google.com/uc?export=view&id=1nTEUAq3YwqsTnvisccDSfn42pD1ksYZc",
  "Tribbie-RMC-Gallagher": "https://drive.google.com/uc?export=view&id=1nvLWjCPSoCHPjxGWzKxXdMOi916ZVr_k",
  "Yukong-Tingyun-FuXuan": "https://drive.google.com/uc?export=view&id=1oBCHRAA9Hefj_6CH3OQcr02qLTel-D3U",
  "RuanMei-Sunday-RMC": "https://drive.google.com/uc?export=view&id=1ofYmCsFTovcQx0T5nxivueJJrnO-ud8r",
  "Tribbie-Sunday-Sparkle": "https://drive.google.com/uc?export=view&id=1pK7dDW-PNkBhjsPE0BX4SG8rRqxhbuPW",
  "Sunday-Sparkle-Tingyun": "https://drive.google.com/uc?export=view&id=1pM-L7_9I-qK-KSt65bXlGlGIPSatTHw9",
  "Robin-RuanMei-Bronya": "https://drive.google.com/uc?export=view&id=1pWJTtbwAgbT88vFyrMsz-D_GCro2Gyyy",
  "Sunday-RMC-Tingyun": "https://drive.google.com/uc?export=view&id=1q0QXU6yVEKdP4kJfgYZpl_TlEYkpQ0u8",
  "Yukong-Sunday-Aventurine": "https://drive.google.com/uc?export=view&id=1qAIwwdDiVjX0cWW_6I0j4pSaJs7RID9o",
  "RuanMei-Sparkle-Bronya": "https://drive.google.com/uc?export=view&id=1qJahkkzsCs0idvZRnxTDAgyCU3zMXb13",
  "Yukong-Sunday-Bronya": "https://drive.google.com/uc?export=view&id=1qTQOjgernI2FnWs0CzB6ch7nmwWEgftS",
  "Cipher-Sunday-RMC": "https://drive.google.com/uc?export=view&id=1qZZOU-t5vvupZh8C36XHYFJcvrCMHdww",
  "Yukong-Sunday-Gallagher": "https://drive.google.com/uc?export=view&id=1r7MUOw11kOdb-CTM-2ubpiqiETKx4pRu",
  "RuanMei-RMC-Tingyun": "https://drive.google.com/uc?export=view&id=1raBC1rhyYWNlhopS143trGe-nmHF4JZr",
  "RuanMei-Sunday-Huohuo": "https://drive.google.com/uc?export=view&id=1rdxP7PaUaQz-U2_ZTI5zOSrDvqFKoiXp",
  "RuanMei-Tingyun-Huohuo": "https://drive.google.com/uc?export=view&id=1rf3kkHeQnjhz6cRi_VDdPAm5cB0YB8QM",
  "Yukong-Sparkle-Bronya": "https://drive.google.com/uc?export=view&id=1rybuIfwYkjwWAilp0vGpc-9Dx8O5wVB5",
  "Tribbie-Sunday-RMC": "https://drive.google.com/uc?export=view&id=1sBQeeERP3senVX4gKGpu0M9QTecg7rjP",
  "Robin-Sparkle-Gallagher": "https://drive.google.com/uc?export=view&id=1sLIDaedow4cHhsfhTS3owuqFcoHtHAvY",
  "Cipher-Sunday-Sparkle": "https://drive.google.com/uc?export=view&id=1tn9satmprwDuJXutzFplpcytw3HkRvDe",
  "Yukong-Bronya-Aventurine": "https://drive.google.com/uc?export=view&id=1uThFNWSizcfvbHoG_9kweEEVm-gDY-6P",
  "Robin-Sunday-Bronya": "https://drive.google.com/uc?export=view&id=1uXzo0q3o2AsNP-8YxjCIoalo4zYF3_DM",
  "Robin-Yukong-Bronya": "https://drive.google.com/uc?export=view&id=1ul0Pbt0WriYsvq6Zk_mOy5qau7fKUAyj",
  "Tribbie-Tingyun-Aventurine": "https://drive.google.com/uc?export=view&id=1wA5dobwCgp0BzcsiTeu4kozr1vEOUQbS",
  "Tribbie-Bronya-Tingyun": "https://drive.google.com/uc?export=view&id=1wOk_qWnGLNHtlgSUMDo11breZoZqTYj3",
  "Cipher-Bronya-Aventurine": "https://drive.google.com/uc?export=view&id=1wZcYEnKw7NqJQiaDmMoy8N2HcQ8fJCpg",
  "Tribbie-Bronya-FuXuan": "https://drive.google.com/uc?export=view&id=1wbacgZh9cGfYi_PbbQwSjl5Y0_VauT1A",
  "Robin-Sunday-RMC": "https://drive.google.com/uc?export=view&id=1welUdieyhRvMWvVZyHBKJcAvTd-3bpPO",
  "Yukong-Tingyun-Gallagher": "https://drive.google.com/uc?export=view&id=1wwfP-mqKZP-UFRweEe1H1Z0t2DRWjV_m",
  "RuanMei-Sunday-Sparkle": "https://drive.google.com/uc?export=view&id=1xPPue1MtMVBeSuOs2wYoPjcGGyyiDC7n",
  "Cipher-Sparkle-Gallagher": "https://drive.google.com/uc?export=view&id=1xQA8fR7mGW56B9zauSCG8c1XlFwJ6DFn",
  "Yukong-Sunday-Tingyun": "https://drive.google.com/uc?export=view&id=1xj6b5P1e3HfglhOLH458ItNMNzelUO4f",
  "Robin-RMC-FuXuan": "https://drive.google.com/uc?export=view&id=1yXvj9ZbqXZ0jpD-xn9SWZuzv6J81Lv0S",
  "Yukong-Sparkle-Aventurine": "https://drive.google.com/uc?export=view&id=1z9BrkDZ6yOEOAVw3MHjdvrQIHaydXVwa",
  "Cipher-Bronya-Huohuo": "https://drive.google.com/uc?export=view&id=1zHmFAOBcua9qQxM04YEy7RNxT-fiDaFt",
  "Jiaoqiu-Tingyun-Aventurine": "https://drive.google.com/file/d/11pQ0QnTl9yjmbxMmJsfetnOnCsejQ0aP/view?usp=sharing",
  "Jiaoqiu-Bronya-RMC": "https://drive.google.com/file/d/15Rbxij31XZUGkRAAfOgwbyQD3HzJrCz8/view?usp=sharing",
  "Jiaoqiu-Sunday-Gallagher": "https://drive.google.com/file/d/15wAZu3sz0mCO4Fxf9VwEkculRIa3yjL7/view?usp=sharing",
  "Jiaoqiu-Sparkle-Bronya": "https://drive.google.com/file/d/18WYAVldI_yinKOLEMtnP9mLgvlBWbShK/view?usp=sharing",
  "Jiaoqiu-Bronya-Tingyun": "https://drive.google.com/file/d/18l6xjvi3rV90HSNX5r9NT78QRDexg74J/view?usp=sharing",
  "Jiaoqiu-Bronya-Gallagher": "https://drive.google.com/file/d/19L6xaGQ3Je7QzkDecmHdR4kMHh-ZCLKU/view?usp=sharing",
  "Jiaoqiu-RMC-Huohuo": "https://drive.google.com/file/d/19iTGUBhNDlgGeTc6O2DW8B7qPFyrm00R/view?usp=sharing",
  "Jiaoqiu-Bronya-Huohuo": "https://drive.google.com/file/d/1A8likDCNT9BL5fEllgOcoWyejuI_NhrK/view?usp=sharing",
  "Jiaoqiu-Sunday-Sparkle": "https://drive.google.com/file/d/1BR0ZMwLGAHMmnMpHUIU4YQAJb6NRcoxc/view?usp=sharing",
  "Jiaoqiu-Sunday-Huohuo": "https://drive.google.com/file/d/1BRIOqajL9pGdaot5u0vCtrJqQdFQaatO/view?usp=sharing",
  "Jiaoqiu-Sparkle-Huohuo": "https://drive.google.com/file/d/1DZG--cIH7YA_rO2_iw3VI8PHs2x_c1mP/view?usp=sharing",
  "Jiaoqiu-Bronya-FuXuan": "https://drive.google.com/file/d/1HNVEdFrQ3yQTLhqFGtlwiNJz-4o38fbF/view?usp=sharing",
  "Jiaoqiu-RMC-FuXuan": "https://drive.google.com/file/d/1HqqX-ZluSA0nr7CSuUfQYTn6S6h2awil/view?usp=sharing",
  "Jiaoqiu-Sparkle-Aventurine": "https://drive.google.com/file/d/1IFnc7AtB3vMZR1gCD1gvBsvbdkVpREDS/view?usp=sharing",
  "Jiaoqiu-Sparkle-FuXuan": "https://drive.google.com/file/d/1NsgMcDi-lwNaYbrD1E9v1Cjk588RmJrD/view?usp=sharing",
  "Robin-Jiaoqiu-Sunday": "https://drive.google.com/file/d/1OYMb1gwRdQLMnTGeZQYyLWCfyHq6ep5t/view?usp=sharing",
  "Jiaoqiu-Sparkle-RMC": "https://drive.google.com/file/d/1ULMCGjmzySajLv3CM9SJSw52wEA7dDPY/view?usp=sharing",
  "Jiaoqiu-RMC-Tingyun": "https://drive.google.com/file/d/1WNcqP0vJaqRpzToZN6qL2hNpU_dOEyKF/view?usp=sharing",
  "Robin-Jiaoqiu-RMC": "https://drive.google.com/file/d/1WPk8RMw7PTWZEQ1zUjDFOdDbujWYwNoR/view?usp=sharing",
  "Jiaoqiu-Sparkle-Tingyun": "https://drive.google.com/file/d/1cTdOrH0IYMfjmVMROmNnE52ybX73eVAK/view?usp=sharing",
  "Jiaoqiu-RMC-Aventurine": "https://drive.google.com/file/d/1e4BAXIagMp-8ePFPcOj1vXFqq1TaUlxj/view?usp=sharing",
  "Jiaoqiu-Sunday-FuXuan": "https://drive.google.com/file/d/1f3RGVTIIWSU3ojaIb0sXsNy_Ul4jUjXz/view?usp=sharing",
  "Robin-Jiaoqiu-Bronya": "https://drive.google.com/file/d/1ief6Y7Sqv2SIwluFNiNq2eZI_8n_zPpg/view?usp=sharing",
  "Robin-Jiaoqiu-Tingyun": "https://drive.google.com/file/d/1mHyQjUGvqPZTY5dyq7ty7KtVPBpGL1fz/view?usp=sharing",
  "Jiaoqiu-Sunday-RMC": "https://drive.google.com/file/d/1qO-yQPT8W5Vd9l3SCubQi1NMPe1negm4/view?usp=sharing",
  "Jiaoqiu-Tingyun-Huohuo": "https://drive.google.com/file/d/1qP4lij2M4L8xrozFq51o6bFC-HX96fk3/view?usp=sharing",
  "Jiaoqiu-Sunday-Bronya": "https://drive.google.com/file/d/1qh0ursxl8VADFvGZucyIIrjR9mLoZ723/view?usp=sharing",
  "Robin-Jiaoqiu-Sparkle": "https://drive.google.com/file/d/1rVO0azIKQzulpiyiC_vm5QDJmmYtd2ce/view?usp=sharing",
  "Jiaoqiu-Sunday-Aventurine": "https://drive.google.com/file/d/1u787SPEgp3Fi9raf-ZCk99U9_jAit1a2/view?usp=sharing",
  "Jiaoqiu-RMC-Gallagher": "https://drive.google.com/file/d/1wmLn86Vk_9Pw9Kol_CnCGAk6yHuwA4Yd/view?usp=sharing",
  "Jiaoqiu-Tingyun-FuXuan": "https://drive.google.com/file/d/1wqUeIRRHlqXkibmImcF0IM2xbVVv3G5d/view?usp=sharing",
  "Jiaoqiu-Sunday-Tingyun": "https://drive.google.com/file/d/1xZ-SNAbFdGlTZS3nTtVYZuKmxYkceupc/view?usp=sharing",
  "Jiaoqiu-Bronya-Aventurine": "https://drive.google.com/file/d/1y0OadfitZSFMkQN8KyLpmlV9aSE6Iqyy/view?usp=sharing",
  "Jiaoqiu-Sparkle-Gallagher": "https://drive.google.com/file/d/1yV5iJffU1905qQCBnotOwy_AIxgWRqiI/view?usp=sharing",
  "Jiaoqiu-Tingyun-Gallagher": "https://drive.google.com/file/d/1yk7qrIMIq7OmM-_sff9VBjKKX8jnLnXD/view?usp=sharing",
}

stacks = {
  "Bronya-RMC-Tingyun": [8, 10],
  "Cipher-Bronya-RMC": [8, 10],
  "Cipher-Bronya-Tingyun": [9, 9],
  "Cipher-RMC-Tingyun": [8, 8],
  "Cipher-Sparkle-Bronya": [8,8],
  "Cipher-Sparkle-RMC": [7,7],
  "Cipher-Sparkle-Tingyun": [7,7],
  "Cipher-Sunday-Bronya": [9,11],
  "Cipher-Sunday-RMC": [8,10],
  "Cipher-Sunday-Sparkle": [9,9],
  "Cipher-Sunday-Tingyun":[10, 10],
  "Robin-Bronya-RMC": [8,10],
  "Robin-Bronya-Tingyun": [10,12],
  "Robin-RMC-Tingyun": [8, 8],
  "Robin-Sparkle-Bronya": [14,14],
  "Robin-Sparkle-RMC": [10, 10],
  "Robin-Sparkle-Tingyun": [10, 10],
  "Robin-Sunday-Bronya": [11,14],
  "Robin-Sunday-RMC": [11, 13],
  "Robin-Sunday-Sparkle": [15,15],
  "Robin-Sunday-Tingyun": [11,15],
  "Sparkle-Bronya-RMC": [11,11],
  "Sparkle-Bronya-Tingyun": [11,11],
  "Sparkle-RMC-Tingyun": [10,10],
  "Sunday-Bronya-RMC": [10,12],
  "Sunday-Bronya-Tingyun": [10,14],
  "Sunday-RMC-Tingyun": [9, 13],
  "Sunday-Sparkle-Bronya": [12, 12],
  "Sunday-Sparkle-RMC": [12, 12],
  "Sunday-Sparkle-Tingyun": [12, 12],
  "Tribbie-Bronya-RMC": [7, 9],
  "Tribbie-Bronya-Tingyun": [7, 9],
  "Tribbie-RMC-Tingyun": [6, 8],
  "Tribbie-Sparkle-Bronya": [8, 8],
  "Tribbie-Sparkle-RMC": [7,7],
  "Tribbie-Sparkle-Tingyun": [7,7],
  "Tribbie-Sunday-Bronya": [9,11],
  "Tribbie-Sunday-RMC": [8,10],
  "Tribbie-Sunday-Sparkle": [9,9],
  "Tribbie-Sunday-Tingyun": [8,10],
  "Yukong-Bronya-RMC": [5, 7],
  "Yukong-Bronya-Tingyun": [7, 9],
  "Yukong-RMC-Tingyun": [6, 6],
  "Yukong-Sparkle-Bronya": [8,8],
  "Yukong-Sparkle-RMC": [7,7],
  "Yukong-Sparkle-Tingyun": [7,7],
  "Yukong-Sunday-Bronya": [7,11],
  "Yukong-Sunday-RMC": [6,8],
  "Yukong-Sunday-Sparkle":[9,9],
  "Yukong-Sunday-Tingyun":[8,10],
  "Cipher-Sunday-Gallagher": [8, 9],
  "Tribbie-Sunday-Gallagher": [8, 9],
  "Tribbie-RMC-Gallagher": [6, 6],
  "Cipher-Bronya-Gallagher": [7,8],
  "Tribbie-Bronya-Gallagher": [7,7],
  "Yukong-Sunday-Gallagher": [6,8],
  "Cipher-RMC-Gallagher": [6,6],
  "Robin-Sunday-Gallagher": [11,13],
  "Yukong-Bronya-Gallagher": [5,7],
  "Cipher-Sunday-Huohuo": [10, 10],
  "Tribbie-Sunday-Huohuo": [8, 10],
  "Tribbie-RMC-Huohuo": [6, 8],
  "Cipher-Bronya-Huohuo": [9,9],
  "Tribbie-Bronya-Huohuo": [7,9],
  "Cipher-RMC-Huohuo": [8,8],
  "Yukong-Sunday-Huohuo": [8,10],
  "Robin-Sunday-Huohuo": [11,13],
  "Cipher-Sparkle-Huohuo": [8,8],
  "Cipher-Sunday-FuXuan": [7,7],
  "Tribbie-Sunday-FuXuan": [5,7],
  "Cipher-Bronya-FuXuan": [6,6],
  "Tribbie-Bronya-FuXuan": [4,6],
  "Tribbie-RMC-FuXuan": [3,5],
  "Cipher-RMC-FuXuan": [2,4],
  "Yukong-Sunday-FuXuan": [5,7],
  "Cipher-Sparkle-FuXuan": [4,4],
  "Tribbie-Sparkle-FuXuan": [4,4],
  "Cipher-Sunday-Aventurine": [8,8],
  "Tribbie-Sunday-Aventurine": [7,8],
  "Tribbie-RMC-Aventurine": [5,6],
  "Cipher-Bronya-Aventurine": [7,7],
  "Tribbie-Bronya-Aventurine": [6,7],
  "Yukong-Sunday-Aventurine": [7,8],
  "Cipher-RMC-Aventurine": [6,6],
  "Robin-Sunday-Aventurine": [10,12],
  "Yukong-RMC-Aventurine": [5,5],
  "RuanMei-Sunday-RMC": [9,11],
  "RuanMei-Sunday-Bronya": [10,11],
  "RuanMei-Bronya-RMC": [8,10],
  "RuanMei-Sunday-Sparkle": [10,10],
  "RuanMei-Sparkle-RMC": [8,8],
  "RuanMei-Sunday-Tingyun": [11,11],
  "RuanMei-Sparkle-Bronya": [9,9],
  "RuanMei-RMC-Tingyun": [9,9],
  "RuanMei-Bronya-Tingyun": [10, 10],
  "RuanMei-Sparkle-Tingyun": [8,8],
  "RuanMei-Sunday-Aventurine": [9,9],
  "RuanMei-Sunday-Huohuo": [11,11],
  "RuanMei-Sunday-Gallagher": [9,10],
  "RuanMei-Sunday-FuXuan": [8,8],
  "Robin-Cipher-Sunday": [10,12],
  "Robin-Tribbie-Sunday": [10,12],
  "Robin-Tribbie-RMC": [7,7],
  "Robin-Cipher-RMC": [7,7],
  "Robin-Cipher-Bronya": [9, 9],
  "Robin-Tribbie-Bronya": [7, 9],
  "Robin-Yukong-Sunday": [8,10],
  "Robin-Cipher-Sparkle": [7,7],
  "Robin-Tribbie-Sparkle": [7,7],
  "Robin-RuanMei-Sunday": [11,13],
  "Cipher-Sparkle-Aven": [5,5],
  "Yukong-RMC-FuXuan": [3,5],
  "Yukong-RMC-Huohuo": [7,7],
  "Yukong-RMC-Gallagher": [4,4]
}